title: bumbleflies | 🦋
email: info@bumbleflies.de
author: bumbleflies UG
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bumbleflies.de" # the base hostname & protocol for your site, e.g. http://example.com

copyright: 'bumbleflies UG [CC by 4.0](https://creativecommons.org/licenses/by/4.0/){:target="_blank"}'

locale: "de-DE"
# https://github.com/kurtsson/jekyll-multiple-languages-plugin#31-using-the-gem
languages: ["de", "en"]
default_locale_in_subfolder: false
exclude_from_localizations: ["assets", "favicon.ico"]

# Build settings
theme: jekyll-agency

repository: bumbleflies/web

include: ['_pages']

# https://jekyllrb.com/docs/troubleshooting/#configuration-problems
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/bumbleflies.jekyll.agency
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CLAUDE.md
  - STAGE3_COMPLETE.md
  - TRANSFORMATION_JOURNEY_CONCEPT.md
  - 404.html
  - beta/
  - docs/

plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
