# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'beta/**'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
