name: Build and Test Jekyll Site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.10"
      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: false
      - name: 🫱 Upload site
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: |
            _site
          retention-days: 1
      - name: 🐍 setup python for test
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"
          cache: "pip"
      - name: 📄 install test requirements
        uses: py-actions/py-dependency-install@v4
        with:
          path: "_tests/requirements.txt"
          update-setuptools: "false"
          update-wheel: "false"
      - name: 🧪 test with pytest
        uses: dariocurr/pytest-summary@main
        with:
          paths: _tests
